package api

import (
	"log/slog"
	"net/http"
	"time"

	"salio/server/internal/middleware"
	"salio/server/internal/models"
)

// SyncHandler handles the offline-first sync routes (Push and Pull).
type SyncHandler struct {
	syncRepo SyncRepository
}

// NewSyncHandler creates a new SyncHandler.
func NewSyncHandler(syncRepo SyncRepository) *SyncHandler {
	return &SyncHandler{syncRepo: syncRepo}
}

// Pull handles GET /v1/sync/pull?last_sync=2026-07-02T10:00:00Z
// Returns all records modified AFTER the provided timestamp.
func (h *SyncHandler) Pull(w http.ResponseWriter, r *http.Request) {
	businessID := middleware.GetBusinessID(r.Context())

	lastSyncStr := r.URL.Query().Get("last_sync")
	var lastSync time.Time
	var err error

	if lastSyncStr == "" {
		// If not provided (first time login), fetch everything from the beginning of time
		lastSync = time.Unix(0, 0).UTC()
	} else {
		lastSync, err = time.Parse(time.RFC3339, lastSyncStr)
		if err != nil {
			respondError(w, http.StatusBadRequest, ErrCodeValidation, "last_sync must be a valid RFC3339 timestamp")
			return
		}
	}

	payload, err := h.syncRepo.Pull(r.Context(), businessID, lastSync)
	if err != nil {
		respondError(w, http.StatusInternalServerError, ErrCodeInternal, "Failed to pull sync data")
		return
	}

	respond(w, http.StatusOK, payload)
}

// Push handles POST /v1/sync/push
// Receives batches of records from the mobile app and upserts them locally.
func (h *SyncHandler) Push(w http.ResponseWriter, r *http.Request) {
	businessID := middleware.GetBusinessID(r.Context())

	var payload models.SyncPayload
	if !decode(w, r, &payload) {
		return
	}

	// We trust the UUIDs generated by the client, but we enforce the business_id 
	// at the database layer (in SyncRepository) to ensure tenants cannot overwrite each other.

	if err := h.syncRepo.Push(r.Context(), businessID, payload); err != nil {
		slog.Error("Sync Push failed", "error", err, "business_id", businessID)
		respondError(w, http.StatusInternalServerError, ErrCodeInternal, "Failed to push sync data: "+err.Error())
		return
	}

	respond(w, http.StatusOK, map[string]string{
		"message": "Sync successful",
	})
}
